import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms & Conditions',
  description: 'Terms and Conditions for using Nexgen Finser website and financial advisory services.',
};

export default function TermsPage() {
  return (
    <div style={{ background: 'var(--bg-light)', minHeight: '100vh', padding: '4rem 0' }}>
      {/* Hero */}
      <div style={{ background: 'linear-gradient(135deg, var(--navy-dark), var(--navy))', color: 'white', padding: '4rem 0', marginBottom: '3rem' }}>
        <div className="container-custom">
          <div style={{ fontFamily: "'Work Sans', sans-serif", fontSize: '0.75rem', letterSpacing: '0.12em', textTransform: 'uppercase', color: 'var(--gold)', marginBottom: '0.75rem', fontWeight: 600 }}>
            Legal
          </div>
          <h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: 'clamp(2rem, 4vw, 3rem)', fontWeight: 700, marginBottom: '0.75rem' }}>
            Terms & Conditions
          </h1>
          <p style={{ color: 'rgba(255,255,255,0.65)', fontSize: '1rem' }}>Last updated: June 2025</p>
        </div>
      </div>

      <div className="container-custom">
        <div style={{ maxWidth: '800px', margin: '0 auto' }}>
          {/* Important Disclaimer Box */}
          <div style={{ background: 'rgba(200,167,93,0.08)', border: '1px solid rgba(200,167,93,0.3)', borderRadius: '0.875rem', padding: '1.5rem', marginBottom: '2rem' }}>
            <div style={{ fontFamily: "'Work Sans', sans-serif", fontWeight: 700, color: 'var(--gold-dark)', marginBottom: '0.5rem', textTransform: 'uppercase', fontSize: '0.75rem', letterSpacing: '0.1em' }}>
              ⚠ Important Disclaimer
            </div>
            <p style={{ fontFamily: "'Inter', sans-serif", fontSize: '0.9rem', lineHeight: 1.7, color: 'var(--text-secondary)' }}>
              <strong>Mutual Fund investments are subject to market risks. Past performance is not indicative of future results. Please read all scheme related documents carefully before investing.</strong> The information on this website is for educational and informational purposes only and does not constitute investment advice or a recommendation to buy or sell any securities.
            </p>
          </div>

          <div className="glass-card" style={{ padding: '3rem' }}>
            {[
              {
                title: '1. Acceptance of Terms',
                content: `By accessing and using the Nexgen Finser website (nexgenfinser.com), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use our website.`,
              },
              {
                title: '2. Nature of Services',
                content: `Nexgen Finser is an AMFI Registered Mutual Fund Distributor (ARN-XXXXXX). We provide mutual fund distribution services and financial planning guidance. 

IMPORTANT: We are NOT a SEBI Registered Investment Advisor (RIA). Our services constitute mutual fund distribution and not investment advisory services under SEBI (Investment Advisers) Regulations, 2013.`,
              },
              {
                title: '3. No Guaranteed Returns',
                content: `All return figures, projections, and illustrations on this website — including those generated by the Wealth Projection Studio calculator — are for ILLUSTRATIVE PURPOSES ONLY. 

• Past performance does not guarantee future results
• Mutual fund returns are subject to market conditions
• The calculators use assumed rates of return that may differ significantly from actual returns
• No returns are guaranteed by Nexgen Finser or any mutual fund company`,
              },
              {
                title: '4. Wealth Projection Studio Calculator',
                content: `The Wealth Projection Studio and all financial calculators on this website are provided as educational tools only. The projections generated:

• Are based on assumed rates of return input by the user
• Do not account for taxes, exit loads, or expense ratios (unless specified)
• Are not personalised investment advice
• Should not be the sole basis for financial decisions
• May differ significantly from actual investment outcomes

Please consult a qualified financial advisor before making investment decisions.`,
              },
              {
                title: '5. Intellectual Property',
                content: `All content on this website, including text, graphics, logos, and software (including the Wealth Projection Studio calculator), is the property of Nexgen Finser and is protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works without explicit written permission.`,
              },
              {
                title: '6. Limitation of Liability',
                content: `Nexgen Finser shall not be liable for any direct, indirect, incidental, or consequential damages arising from:
• Your use or inability to use our website
• Any investment decisions made based on information from our website
• Inaccuracies or errors in calculator projections
• Market losses on investments made through our distribution services`,
              },
              {
                title: '7. User Conduct',
                content: `You agree not to:
• Use our website for any unlawful purpose
• Attempt to gain unauthorised access to any part of our website
• Transmit any harmful or malicious code
• Misrepresent your identity or qualifications when contacting us`,
              },
              {
                title: '8. Links to Third-Party Websites',
                content: `Our website may contain links to third-party websites (AMFI, SEBI, CAMS, CDSL, etc.). These links are provided for convenience only. We have no control over the content of these sites and accept no responsibility for them.`,
              },
              {
                title: '9. AMFI Compliance',
                content: `As an AMFI Registered MFD, Nexgen Finser complies with all AMFI codes of conduct and SEBI regulations applicable to mutual fund distributors. Our ARN number (ARN-XXXXXX) is displayed prominently on our website in compliance with AMFI requirements.`,
              },
              {
                title: '10. Governing Law',
                content: `These Terms are governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in Kota, Rajasthan.`,
              },
              {
                title: '11. Contact Information',
                content: `For any questions about these Terms, please contact:

Nexgen Finser
123 Finance Square, Kota, Rajasthan 324001
Email: info@nexgenfinser.com
Phone: +91-98765-43210`,
              },
            ].map((section) => (
              <div key={section.title} style={{ marginBottom: '2.5rem' }}>
                <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: '1.25rem', fontWeight: 600, color: 'var(--navy)', marginBottom: '1rem', paddingBottom: '0.5rem', borderBottom: '2px solid rgba(200,167,93,0.2)' }}>
                  {section.title}
                </h2>
                <p style={{ fontFamily: "'Inter', sans-serif", fontSize: '0.9375rem', lineHeight: 1.8, color: 'var(--text-secondary)', whiteSpace: 'pre-line' }}>
                  {section.content}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
